### ISSUE TITLE
Could not parse data from wasm_search

### ISSUE THREAD

**Issue by alexkehayias** [jameslittle230/stork#285]
I wasn't able to repeat the error after reloading the page but I noticed the following in the console.

(Web page source [here](https://notes.alexkehayias.com/search/))

```
panicked at 'range end index 10 out of range for slice of length 9', src/index_versions/v3/search/entry_and_intermediate_excerpts.rs:144:33

Stack:

Error
    at l.wbg.__wbg_new_59cb74e423758ede (https://files.stork-search.net/stork.js:1:2411)
    at https://files.stork-search.net/stork.wasm:wasm-function[209]:0x36f09
    at https://files.stork-search.net/stork.wasm:wasm-function[829]:0x4a5f5
    at https://files.stork-search.net/stork.wasm:wasm-function[342]:0x3fade
    at https://files.stork-search.net/stork.wasm:wasm-function[493]:0x459dc
    at https://files.stork-search.net/stork.wasm:wasm-function[647]:0x492fa
    at https://files.stork-search.net/stork.wasm:wasm-function[691]:0x49ac6
    at https://files.stork-search.net/stork.wasm:wasm-function[551]:0x47397
    at https://files.stork-search.net/stork.wasm:wasm-function[518]:0x465be
    at https://files.stork-search.net/stork.wasm:wasm-function[303]:0x3d6c0


l.wbg.__wbg_error_4bb6c2a97407129a @ stork.js:246


entity.ts:187 StorkError: Could not parse data from wasm_search. If you see this, please file a bug: https://jil.im/storkbug null
    at new t (storkError.ts:3:5)
    at Object.t.resolveSearch (searchData.ts:48:11)
    at e.performSearch (entity.ts:178:20)
    at e.handleInputEvent (entityDom.ts:370:17)
    at HTMLInputElement.inputInputEvent (entityDom.ts:110:14)
e.performSearch @ entity.ts:187
stork.js:246 panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/wasm/../unsupported/mutex.rs:23:9

Stack:

Error
    at l.wbg.__wbg_new_59cb74e423758ede (https://files.stork-search.net/stork.js:1:2411)
    at https://files.stork-search.net/stork.wasm:wasm-function[209]:0x36f09
    at https://files.stork-search.net/stork.wasm:wasm-function[829]:0x4a5f5
    at https://files.stork-search.net/stork.wasm:wasm-function[342]:0x3fade
    at https://files.stork-search.net/stork.wasm:wasm-function[493]:0x459dc
    at https://files.stork-search.net/stork.wasm:wasm-function[647]:0x492fa
    at https://files.stork-search.net/stork.wasm:wasm-function[691]:0x49ac6
    at https://files.stork-search.net/stork.wasm:wasm-function[178]:0x3460d
    at https://files.stork-search.net/stork.wasm:wasm-function[556]:0x4758c
    at https://files.stork-search.net/stork.wasm:wasm-function[533]:0x46c2e
```

**Comment by jameslittle230** [comment]
Hm - thanks for the report. You should never see this, and I'm hoping this was just a one-off blip. If you're able to reproduce this, please reopen the bug. :)
